### ISSUE TITLE
Vrep demo not working

### ISSUE THREAD

**Issue by xepost** [lagadic/demo_pioneer#2]
Hi,
 I installed  vrep_ros_bridge,using this [link.](https://github.com/lagadic/vrep_ros_bridge) and installed 
[demo_pioneer](https://github.com/lagadic/demo_pioneer). When I try to run it with Vrep  I receive  by using this command

roslaunch demo_pioneer demo-visual-servo-pioneer-simulation.launch

I get and  error saying that  demo-visual-servo-pioneer-simulation.launch does not exist. That  file does not exist in both on my folder location and the github rep. 

I am able to run  real pioneer using 
roslaunch demo_pioneer pioneer-teleop.launch
and  vrep_ros_bridge installation loads and initializes successfully at vrep startup.

I can  load Pioneer_p3dxMOD2.ttt file  but the camera  model does not render. I would be glad if you can  help me on running this  demo on vrep. 

Are you planning to publish codes for "Control of Robots in V-REP via Matlab/Simulink and ROS" ?

My system is Ubuntu 12.04.03x64 using Ros Hydro and V-REP_PRO_EDU_V3_1_2_64. Thanks for the helping out.

**Comment by enddl22** [comment]
Hello, thank you for the excellent works.
I tried to run the visual servoing demo simulation program (demo-visual-servo-pioneer-simulation.launch), but the pioneer in VREP keeps turning right after approaching the QR code. 

I did the followings
https://github.com/lagadic/demo_pioneer
https://github.com/lagadic/vrep_ros_bridge
and ViSP installation.

All other things such as vrep_ros_bridge, ViSP, and VREP look working since I can see the QR code tracking window with the title "visp_auto_tracker debug display" and image streaming from VREP using image_view. 

I did the following steps:
1. run roscore
2. start VREP (All handlers are loaded)
3. load Pioneer_p3dxMOD2.ttt into VREP.
4. launch script "demo-visual-servo-pioneer-simulation.launch"
5. run VREP and my little red guy always turns right.

Here are my versions of software packages.
ROS: Indigo (roscpp version: 1.11.10)
VREP: 3.2.0(rev.6) 64bit
demo_pioneers: git clone https://github.com/lagadic/demo_pioneer.git (branch: master)
vrep_ros_bridge: https://github.com/lagadic/vrep_ros_bridge (branch: indigo-devel)

If you need more information, please let me know.
Cheers,

**Comment by jokla** [comment]
Hi enddl22,

Thank you for the feedback and the detailed explanation. 

We changed the orientation of the camera frame in the plugin but the scene Pioneer_p3dxMOD2.ttt  was not updated. I pushed the new good version of the scene some minutes ago in vrep_ros_bridge. Basically I just rotated the camera around the z axes about 180 degree.

Now it should works, let me know,

Cheers,

Giovanni

**Comment by enddl22** [comment]
Awesome, it works like charm.
Thanks.
