### ISSUE TITLE
How exactly to tune the values of lambda_adapt?

### ISSUE THREAD

**Issue by Gowresh7** [lagadic/demo_pioneer#7]
Is there a thumb rule that need to be followed to tune the values of lambda_adapt?

**Comment by fspindle** [comment]
See [vpAdaptiveGain](https://visp-doc.inria.fr/doxygen/visp-daily/classvpAdaptiveGain.html) doc for a general description of the parameters.

- Modify the code to not use adaptive gain replacing `task.setLambda(lambda_adapt);` by `task.setLambda(lambda);`
- To tune adaptive gain first value lambda(0) which corresponds to the gain when the error is close to zero, move the robot close to the desired position, then increase value of `lambda` (start with `lambda = 1.0`) until you observe robot oscillations. A good value is a value that doesn't bring oscillations
- To tune adaptive gain second value lambda(oo) which corresponds to the gain when the error is very high, move the robot to your initial position wrt the target in order to get a large visual servoing error (s-s*). Set `lambda` to a small value like `0.1` and increase this value until vision is no more able to track your features or robot becomes dangerous with a velocity too high.
- The last value lambda'(0) is the slope of the curve lambda_adapt = f(s-s*) when s-s* = 0. You can keep it to 30

**Comment by Gowresh7** [comment]
Thank You, Fabien..!! It did the trick..!!
